backend:
  name: github
  repo: all-voices-org/all-voices-org
  branch: main

# local_backend: true

media_folder: 'public/assets/uploads'
public_folder: '/assets/uploads'
publish_mode: editorial_workflow

i18n:
  structure: multiple_folders
  locales: [en, es, fr, ar, sw, ht]
  default_locale: en

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/content/docs'
    create: false
    i18n: true
    sortable_fields: []
    fields:
      - { name: 'title', widget: 'string', i18n: true, duplicate: true }
      - { name: 'body', widget: 'markdown', i18n: true, duplicate: true }

  - name: 'resources'
    label: 'Resources'
    folder: 'src/content/resources'
    create: true
    i18n: true
    summary: '{{content.0.type}}: {{title}}'
    fields:
      - {
          name: 'title',
          label: 'Resource Title',
          widget: 'string',
          i18n: true,
          duplicate: true
        }
      - {
          name: 'summary',
          label: 'Resource Summary',
          widget: 'text',
          i18n: true,
          duplicate: true
        }
      - name: content
        label: 'Resource Content'
        hint: 'Add the content for the resource. Only one item is allowed.'
        widget: list
        i18n: true
        duplicate: true
        min: 1
        max: 1
        required: true
        collapsed: false
        types:
          - name: document
            label: 'Document'
            summary: "{{title}} - {{body | truncate(50, '...')}}"
            widget: object
            i18n: true
            duplicate: true
            fields:
              - {
                  name: 'body',
                  label: 'Body',
                  widget: 'markdown',
                  i18n: true,
                  duplicate: true
                }

          - name: pdf
            label: 'PDF File'
            summary: '{{file}}'
            widget: object
            i18n: true
            duplicate: true
            fields:
              - {
                  name: 'description',
                  label: 'Description',
                  widget: 'text',
                  i18n: true,
                  duplicate: true,
                  required: false
                }
              - {
                  name: 'file',
                  label: 'File Upload',
                  widget: 'file',
                  i18n: true,
                  duplicate: true
                }

          - name: 'video'
            label: 'Video File'
            summary: '{{file}}'
            widget: object
            i18n: true
            duplicate: true
            fields:
              - {
                  name: 'description',
                  label: 'Description',
                  widget: 'text',
                  i18n: true,
                  duplicate: true,
                  required: false
                }
              - {
                  name: 'file',
                  label: 'File Upload',
                  widget: 'file',
                  i18n: true,
                  duplicate: true
                }

          - name: 'link'
            label: 'External Link'
            summary: '{{url}}'
            widget: object
            i18n: true
            duplicate: true
            fields:
              - {
                  name: 'url',
                  label: 'URL',
                  widget: 'string',
                  i18n: true,
                  duplicate: true
                }
